
import { WordPair } from './types';

export const WORD_PAIRS: WordPair[] = [
  { civil: 'Oiseau', undercover: 'Papillon' },
  { civil: 'Éclair', undercover: 'Tonnerre' },
  { civil: 'Cidre', undercover: 'Bière' },
  { civil: 'Fondue', undercover: 'Raclette' },
  { civil: 'Taxi', undercover: 'Uber' },
  { civil: 'Pizza', undercover: 'Burger' },
  { civil: 'Plage', undercover: 'Piscine' },
  { civil: 'Vin', undercover: 'Champagne' },
  { civil: 'Montagne', undercover: 'Forêt' },
  { civil: 'Chocolat', undercover: 'Caramel' },
  { civil: 'Chien', undercover: 'Chat' },
  { civil: 'Guitare', undercover: 'Violon' },
  { civil: 'Thé', undercover: 'Café' },
  { civil: 'Miel', undercover: 'Sirop d\'érable' },
  { civil: 'Mer', undercover: 'Océan' },
  { civil: 'Soleil', undercover: 'Lune' },
  { civil: 'Avion', undercover: 'Hélicoptère' },
  { civil: 'Savon', undercover: 'Gel Douche' },
  { civil: 'Ski', undercover: 'Surf' },
  { civil: 'Cravate', undercover: 'Nœud papillon' },
  { civil: 'Piano', undercover: 'Clavier' },
  { civil: 'Laptop', undercover: 'Tablette' },
  { civil: 'Baskets', undercover: 'Chaussures' },
  { civil: 'Veste', undercover: 'Manteau' },
  { civil: 'Stylo', undercover: 'Crayon' },
  { civil: 'Livre', undercover: 'Magazine' },
  { civil: 'Film', undercover: 'Série' },
  { civil: 'Velo', undercover: 'Trottinette' },
  { civil: 'Fruit', undercover: 'Légume' },
  { civil: 'Sucre', undercover: 'Sel' },
  { civil: 'Beurre', undercover: 'Margarine' },
  { civil: 'Pain', undercover: 'Baguette' },
  { civil: 'Fromage', undercover: 'Yaourt' },
  { civil: 'Poulet', undercover: 'Dinde' },
  { civil: 'Steak', undercover: 'Saucisse' },
  { civil: 'Astronaute', undercover: 'Cosmonaute' },
  { civil: 'Désert', undercover: 'Savane' },
  { civil: 'Cascade', undercover: 'Rivière' },
  { civil: 'Diamant', undercover: 'Cristal' },
  { civil: 'Château', undercover: 'Palais' },
  { civil: 'Lion', undercover: 'Tigre' },
  { civil: 'Baleine', undercover: 'Dauphin' },
  { civil: 'Pingouin', undercover: 'Manchot' },
  { civil: 'Tapis', undercover: 'Moquette' },
  { civil: 'Rideau', undercover: 'Store' },
  { civil: 'Lampe', undercover: 'Lanterne' },
  { civil: 'Bougie', undercover: 'Briquet' },
  { civil: 'Miroir', undercover: 'Vitre' },
  { civil: 'Cadre', undercover: 'Tableau' },
  { civil: 'Horloge', undercover: 'Montre' },
  { civil: 'Canapé', undercover: 'Fauteuil' },
  { civil: 'Lit', undercover: 'Hamac' },
  { civil: 'Oreiller', undercover: 'Coussin' },
  { civil: 'Assiette', undercover: 'Bol' },
  { civil: 'Verre', undercover: 'Tasse' },
  { civil: 'Fourchette', undercover: 'Couteau' },
  { civil: 'Casserole', undercover: 'Poêle' },
  { civil: 'Four', undercover: 'Micro-ondes' },
  { civil: 'Frigo', undercover: 'Congélateur' },
  { civil: 'Balai', undercover: 'Aspirateur' },
  { civil: 'Parapluie', undercover: 'Imperméable' },
  { civil: 'Valise', undercover: 'Sac à dos' },
  { civil: 'Portefeuille', undercover: 'Porte-monnaie' },
  { civil: 'Ciseaux', undercover: 'Cutter' },
  { civil: 'Colle', undercover: 'Scotch' },
  { civil: 'Marteau', undercover: 'Tournevis' },
  { civil: 'Clou', undercover: 'Vis' },
  { civil: 'Échelle', undercover: 'Escabeau' },
  { civil: 'Pinceau', undercover: 'Rouleau' },
  { civil: 'Dentifrice', undercover: 'Bain de bouche' },
  { civil: 'Parfum', undercover: 'Déodorant' },
  { civil: 'Maquillage', undercover: 'Rouge à lèvres' },
  { civil: 'Rasoir', undercover: 'Tondeuse' },
  { civil: 'Serviette', undercover: 'Peignoir' },
  { civil: 'Lunettes', undercover: 'Lentilles' },
  { civil: 'Bague', undercover: 'Bracelet' },
  { civil: 'Collier', undercover: 'Boucles d\'oreilles' },
  { civil: 'Batterie', undercover: 'Percussions' },
  { civil: 'Trompette', undercover: 'Saxophone' },
  { civil: 'Flûte', undercover: 'Clarinette' },
  { civil: 'Chant', undercover: 'Opéra' },
  { civil: 'Danse', undercover: 'Ballet' },
  { civil: 'Peinture', undercover: 'Dessin' },
  { civil: 'Sculpture', undercover: 'Poterie' },
  { civil: 'Photographie', undercover: 'Vidéo' },
  { civil: 'Poésie', undercover: 'Roman' },
  { civil: 'Journal', undercover: 'Blog' },
  { civil: 'Radio', undercover: 'Podcast' },
  { civil: 'Cirque', undercover: 'Cabaret' },
  { civil: 'Magie', undercover: 'Illusion' },
  { civil: 'Jeu de société', undercover: 'Puzzle' },
  { civil: 'Football', undercover: 'Rugby' },
  { civil: 'Tennis', undercover: 'Ping-pong' },
  { civil: 'Basket', undercover: 'Handball' },
  { civil: 'Natation', undercover: 'Plongée' },
  { civil: 'Cyclisme', undercover: 'VTT' },
  { civil: 'Course à pied', undercover: 'Marche' },
  { civil: 'Gymnastique', undercover: 'Yoga' },
  { civil: 'Escalade', undercover: 'Alpinisme' },
  { civil: 'Boxe', undercover: 'Karaté' },
  { civil: 'Escrime', undercover: 'Tir à l\'arc' },
  { civil: 'Golf', undercover: 'Minigolf' },
  { civil: 'Bowling', undercover: 'Billard' },
  { civil: 'Échecs', undercover: 'Dames' },
  { civil: 'Cartes', undercover: 'Poker' },
  { civil: 'Casino', undercover: 'Loterie' },
  { civil: 'Parc', undercover: 'Jardin' },
  { civil: 'Zoo', undercover: 'Aquarium' },
  { civil: 'Musée', undercover: 'Galerie' },
  { civil: 'Bibliothèque', undercover: 'Librairie' },
  { civil: 'Boulangerie', undercover: 'Pâtisserie' },
  { civil: 'Boucherie', undercover: 'Poissonnerie' },
  { civil: 'Marché', undercover: 'Foire' },
  { civil: 'Banque', undercover: 'Assurance' },
  { civil: 'Mairie', undercover: 'Préfecture' },
  { civil: 'Poste', undercover: 'Colis' },
  { civil: 'Gare', undercover: 'Aéroport' },
  { civil: 'Parking', undercover: 'Garage' },
  { civil: 'Pont', undercover: 'Tunnel' },
  { civil: 'Route', undercover: 'Autoroute' },
  { civil: 'Rue', undercover: 'Avenue' },
  { civil: 'Ville', undercover: 'Village' },
  { civil: 'Pays', undercover: 'Continent' },
  { civil: 'Planète', undercover: 'Étoile' },
  { civil: 'Galaxie', undercover: 'Univers' },
  { civil: 'Nuage', undercover: 'Brouillard' },
  { civil: 'Pluie', undercover: 'Neige' },
  { civil: 'Grêle', undercover: 'Tempête' },
  { civil: 'Vent', undercover: 'Ouragan' },
  { civil: 'Vague', undercover: 'Marée' },
  { civil: 'Sable', undercover: 'Galets' },
  { civil: 'Coquillage', undercover: 'Corail' },
  { civil: 'Algues', undercover: 'Mousse' },
  { civil: 'Arbre', undercover: 'Arbuste' },
  { civil: 'Fleur', undercover: 'Plante' },
  { civil: 'Graine', undercover: 'Noyau' },
  { civil: 'Herbe', undercover: 'Pelouse' },
  { civil: 'Colline', undercover: 'Vallée' },
  { civil: 'Grotte', undercover: 'Souterrain' },
  { civil: 'Volcan', undercover: 'Cratère' },
  { civil: 'Île', undercover: 'Presqu\'île' },
  { civil: 'Brouette', undercover: 'Chariot' },
  { civil: 'Éponge', undercover: 'Gant de toilette' },
  { civil: 'Câble', undercover: 'Fil' },
  { civil: 'Prise', undercover: 'Interrupteur' },
  { civil: 'Piles', undercover: 'Batterie' },
  { civil: 'Calculatrice', undercover: 'Abaque' },
  { civil: 'Compas', undercover: 'Équerre' },
  { civil: 'Règle', undercover: 'Mètre' },
  { civil: 'Ciment', undercover: 'Béton' },
  { civil: 'Brique', undercover: 'Parpaing' }
];

export const PLAYER_COLORS = [
  'bg-yellow-500', 'bg-amber-600', 'bg-orange-500', 'bg-stone-400',
  'bg-yellow-600', 'bg-amber-700', 'bg-slate-500', 'bg-yellow-700',
  'bg-orange-600', 'bg-amber-500', 'bg-stone-500', 'bg-yellow-400'
];
